[package]
name = "response"
version = "0.1.0"
edition = "2024"

[dependencies]
code = { path = "../code" }

actix-web = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }