[package]
name = "code"
version = "0.1.0"
edition = "2024"

[lib]
name = "code"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
